"""EXPLORATION — NOT USED FOR THE FINAL STAGE-1 MODEL.

The shipped Stage-1 model (ckpt/stage1.pt) was trained on data/ generated by the
plain forward generator in `generator.py`. That model scores 86.9% on the
in-distribution held-out set but only 16.7% on the curated validation_36 <=6 bin,
because the forward-random generator starves the consuming/discharging rules
(R=0, NEGI=8, IMPE 836) while ORI/ANDI dominate.

This module is the fix I explored for that barrier: goal-directed named-theorem
template families that inject the starved rules (R, IMPE, NEGE, NEGI, BOTE). Each
is hand-checked against verify.py and re-checked by verify_text. With richer
depth-1/2 formula arguments they yield many distinct theorems that survive dedup,
rebalancing the distinct-theorem rule histogram (IMPE 14.7k, NEGE 9.5k, NEGI 3.2k,
BOTE 6.0k, R 3.0k on an n=400k pool).

It is kept for the write-up and future work, but the FINAL submission does not use
it. To regenerate the rebalanced (unused) dataset for comparison:

    from nd.generator_templates import sample_proof_rebalanced
    # then drive it exactly like scripts/gen_data.py drives sample_proof

See log.md ("Generator rebalance") for the full story.
"""
import random

from nd_verify import verify_text
from nd_verify.verify import BOT
from .formula import size, ATOMS
from .generator import (Builder, rand_formula, gen_local, gen_impi, gen_negi,
                        gen_ore)


def _small(rng):
    """Template argument formulas: mostly depth 1-2 so each family yields many
    distinct theorems that survive dedup (atom-only versions collapse and their
    canonical forms are exactly the excluded validation set)."""
    for _ in range(5):
        f = rand_formula(rng, rng.choice([0, 1, 1, 2, 2]), p_atom=0.45)
        if size(f) <= 6:
            return f
    return ('atom', rng.choice(ATOMS))


def gen_modus_ponens(rng):
    A, B = _small(rng), _small(rng)
    b = Builder()
    p1, _ = b.add(0, ('imp', A, B), 'PR', [])
    p2, _ = b.add(0, A, 'PR', [])
    b.add(0, B, 'IMPE', [p1, p2])
    return b.text([('imp', A, B), A], B)


def gen_modus_tollens(rng):
    A, B = _small(rng), _small(rng)
    imp, nB, nA = ('imp', A, B), ('not', B), ('not', A)
    b = Builder()
    p1, _ = b.add(0, imp, 'PR', [])
    p2, _ = b.add(0, nB, 'PR', [])
    s, _ = b.add(1, A, 'AS', [])
    e1, _ = b.add(1, B, 'IMPE', [p1, s])
    e2, _ = b.add(1, BOT, 'NEGE', [e1, p2])
    b.add(0, nA, 'NEGI', [s, e2])
    return b.text([imp, nB], nA)


def gen_hypothetical_syllogism(rng):
    A, B, C = _small(rng), _small(rng), _small(rng)
    ab, bc, ac = ('imp', A, B), ('imp', B, C), ('imp', A, C)
    b = Builder()
    p1, _ = b.add(0, ab, 'PR', [])
    p2, _ = b.add(0, bc, 'PR', [])
    s, _ = b.add(1, A, 'AS', [])
    e1, _ = b.add(1, B, 'IMPE', [p1, s])
    e2, _ = b.add(1, C, 'IMPE', [p2, e1])
    b.add(0, ac, 'IMPI', [s, e2])
    return b.text([ab, bc], ac)


def gen_weakening(rng):
    """B |- ( A > B ): assume A, reiterate B (R), close. Injects R."""
    A, B = _small(rng), _small(rng)
    b = Builder()
    p1, _ = b.add(0, B, 'PR', [])
    s, _ = b.add(1, A, 'AS', [])
    e, _ = b.add(1, B, 'R', [p1])
    b.add(0, ('imp', A, B), 'IMPI', [s, e])
    return b.text([B], ('imp', A, B))


def gen_negative_paradox(rng):
    """( ~ A ) |- ( A > B )."""
    A, B = _small(rng), _small(rng)
    nA = ('not', A)
    b = Builder()
    p1, _ = b.add(0, nA, 'PR', [])
    s, _ = b.add(1, A, 'AS', [])
    e1, _ = b.add(1, BOT, 'NEGE', [s, p1])
    e2, _ = b.add(1, B, 'BOTE', [e1])
    b.add(0, ('imp', A, B), 'IMPI', [s, e2])
    return b.text([nA], ('imp', A, B))


def gen_explosion(rng):
    """( A & ( ~ A ) ) |- B."""
    A, B = _small(rng), _small(rng)
    conj = ('and', A, ('not', A))
    b = Builder()
    p1, _ = b.add(0, conj, 'PR', [])
    n2, _ = b.add(0, A, 'ANDE1', [p1])
    n3, _ = b.add(0, ('not', A), 'ANDE2', [p1])
    n4, _ = b.add(0, BOT, 'NEGE', [n2, n3])
    b.add(0, B, 'BOTE', [n4])
    return b.text([conj], B)


def gen_dn_intro(rng):
    """A |- ( ~ ( ~ A ) )."""
    A = _small(rng)
    nA, nnA = ('not', A), ('not', ('not', A))
    b = Builder()
    p1, _ = b.add(0, A, 'PR', [])
    s, _ = b.add(1, nA, 'AS', [])
    e, _ = b.add(1, BOT, 'NEGE', [p1, s])
    b.add(0, nnA, 'NEGI', [s, e])
    return b.text([A], nnA)


def gen_dn_elim(rng):
    """( ~ ( ~ A ) ) |- A."""
    A = _small(rng)
    nnA = ('not', ('not', A))
    b = Builder()
    p1, _ = b.add(0, nnA, 'PR', [])
    b.add(0, A, 'DN', [p1])
    return b.text([nnA], A)


TEMPLATES = [gen_modus_ponens, gen_modus_tollens, gen_hypothetical_syllogism,
             gen_weakening, gen_negative_paradox, gen_explosion, gen_dn_intro,
             gen_dn_elim]


def gen_template(rng):
    return rng.choice(TEMPLATES)(rng)


_STRATEGIES = ['local', 'impi', 'negi', 'ore', 'template']


def sample_proof_rebalanced(rng, weights=(3, 2, 1, 1, 6), long_bias=False):
    """Rebalanced sampler (templates weighted highest). UNUSED by the final
    submission; see module docstring."""
    strat = rng.choices(_STRATEGIES, weights=weights)[0]
    if strat == 'local':
        text = gen_local(rng, rng.randint(5 if long_bias else 2, 6))
    elif strat == 'impi':
        text = gen_impi(rng, rng.randint(5 if long_bias else 3, 6))
    elif strat == 'negi':
        text = gen_negi(rng)
    elif strat == 'ore':
        text = gen_ore(rng)
    else:
        text = gen_template(rng)
    if text is None:
        return None
    ok, _, nl = verify_text(text)
    if not ok or not (2 <= nl <= 6):
        return None
    return text
